version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - cd <server/>
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
    build-and-test-server:
      jobs:
        - build-and-test
